#!/bin/zsh

###############################################################################
# setup-brew
#
# A shell script to automate system tool setup for Mac OS X.
###############################################################################


###############################################################################
# Install Xcode command line tools
###############################################################################
echo "Installing Xcode Command Line Tools..."
xcode-select --install


###############################################################################
# Check for Homebrew, else install
###############################################################################
echo "Checking for, or Installing Homebrew..."
if [ -z `command -v brew` ]; then
    echo "Brew is missing! Installing it..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi;


###############################################################################
# Make sure we're on latest Homebrew
###############################################################################
echo "Homebrew: updating..."
brew update


###############################################################################
# Upgrade any already-installed formulae
###############################################################################
echo "Homebrew: upgrading..."
brew upgrade


###############################################################################
# Install utilities
###############################################################################
echo "Homebrew: updating unix tools..."
brew install zsh
brew install homebrew/cask-fonts/font-fira-mono-for-powerline


###############################################################################
# Install binaries and other packages
###############################################################################
echo "Homebrew: installing binaries and other packages..."
brew install ffmpeg
brew install git
brew install qlmarkdown
brew install mackup
cat > ~/.mackup.cfg << EOF
[storage]
engine = icloud
directory = .config/mackup
EOF
brew install node
brew install nvm
brew install yarn
brew install

###############################################################################
# Run Homebrew cleanup to remove installation/cached files
###############################################################################
echo "Homebrew: cleaning up..."
brew cleanup


###############################################################################
# Install applications with Homebrew Cask
###############################################################################
echo "Homebrew Cask: installing apps..."
brew --cask install 1password
brew --cask install docker
# brew --cask install dropbox
brew --cask install google-chrome
brew --cask install google-drive-file-stream
brew --cask install iterm2
brew --cask install slack
brew --cask install spotify
brew --cask install visual-studio-code
brew --cask install flycut
brew --cask install miro
brew --cask install zoomus
brew --cask install telegram
brew --cask install inkscape
brew --cask install vlc
brew --cask install tunnelblick



###############################################################################
# Cleanup
###############################################################################
brew cask cleanup


###############################################################################
# Install applications with mas-cli (Mac App Store CLI)
###############################################################################
echo "mas-cli: installing Mac App Store apps..."
# xcode
mas install 497799835
# WiFi Explorer
mas install 494803304
#Moom
mas install 419330170
#WISO Steuer 2022
mas install 1573428744
#GarageBand
mas install 682658836


###############################################################################
# Install java stuff etc...
###############################################################################
curl -s "https://get.sdkman.io" | bash
sdk i java
sdk i groovy
sdk i gradle
sdk i kotlin



echo "macOS Config, Dev Tools, Apps are Done Setup!"
